server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      max-lifetime: 30000         # 30 segundos, evita que Hikari use conexiones cerradas
      connection-timeout: 20000   # Tiempo máximo para obtener una conexión del pool
      validation-timeout: 5000    # Tiempo para validar la conexión
      maximum-pool-size: 10       # Número máximo de conexiones en el pool
      minimum-idle: 2             # Conexiones mínimas ociosas
      keepalive-time: 15000       # Hikari envía un "ping" cada 15s para mantenerlas activas
      connection-test-query: SELECT 1  # Verifica conexiones antes de usarlas

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY}
    user:
      generator: auth-service
