server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Mantén esto en 'update' para que Hibernate ajuste la base de datos en cada inicio.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always  # Ejecutará scripts siempre que arranque la aplicación

security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY}
    user:
      generator: auth-service
